"""Data-plane tests: the runnable half of the anti-leakage checklist.

Reads ``data/raw/BTCUSDT_1h.parquet``, ``data/raw/BTCUSDT_1h_report.json`` and
``data/raw/BTCUSDT_1h_gaps.csv``. Writes nothing.

A checklist that lives only in prose is a checklist nobody runs. Every test here
corresponds to one leakage check, and the fatal ones say so.
"""

from __future__ import annotations

import hashlib
import json
from math import gcd
from pathlib import Path

import polars as pl
import pytest

from itransformer_btc.budget import COMMITTED_TRAIN_BUDGET, budget_table
from itransformer_btc.config import (
    BARS_ACTUAL,
    BARS_EXPECTED,
    DATA_END,
    DATA_START,
    FIRST_ORIGIN,
    GAP_BLOCKS,
    INPUT_SHA256,
    MISSING_BARS,
    ORIGIN_SPACING_MONTHS,
    ORIGINS,
    TEST_BLOCKS,
    WINDOW_SPAN,
    origin_grid,
)
from itransformer_btc.segments import (
    DEFAULT_PARQUET,
    HOUR_MS,
    build_segments,
    load_bars,
    usable_mask,
)
from itransformer_btc.windows import enumerate_windows

RAW = Path("data/raw")


@pytest.fixture(scope="session")
def frame() -> pl.DataFrame:
    return usable_mask(load_bars(DEFAULT_PARQUET))


@pytest.fixture(scope="session")
def report() -> dict:
    return json.loads((RAW / "BTCUSDT_1h_report.json").read_text())


@pytest.fixture(scope="session")
def budgets(frame: pl.DataFrame):
    return budget_table(frame)


# -- artifact integrity ------------------------------------------------------


def test_parquet_rows_equal_bars_actual(frame: pl.DataFrame, report: dict) -> None:
    """FATAL. The runnable form of the no-imputation rule.

    Equality here rules out a reindexed-and-filled grid: a forward-filled
    artifact would hold ``bars_expected`` rows, not ``bars_actual``.
    """
    assert frame.height == report["bars_actual"] == BARS_ACTUAL
    assert report["bars_expected"] == BARS_EXPECTED
    assert frame.height < BARS_EXPECTED, "a full grid means imputation happened"


def test_no_bar_outside_the_half_open_window(frame: pl.DataFrame) -> None:
    """The boundary bar at 2026-08-01T00:00 must be gone (the window is end-exclusive)."""
    assert frame.get_column("ts_ms").min() >= int(DATA_START.timestamp() * 1000)
    assert frame.get_column("ts_ms").max() < int(DATA_END.timestamp() * 1000)


def test_report_reconciles_with_the_gaps_file(report: dict) -> None:
    """Two artifacts describing the same data must agree.

    Gap *detection* was always right; only counts derived from ``len(df)`` were
    wrong, so the report's ``missing_bars`` contradicted its own gaps file.
    """
    gaps = pl.read_csv(RAW / "BTCUSDT_1h_gaps.csv")
    assert gaps.height == report["gap_blocks"] == GAP_BLOCKS
    assert gaps.get_column("missing_bars").sum() == report["missing_bars"]
    assert report["missing_bars"] == MISSING_BARS
    assert report["bars_expected"] - report["bars_actual"] == MISSING_BARS


def test_artifact_vintage_is_recorded(report: dict) -> None:
    """Without a hash, no run can prove which data vintage it consumed."""
    digests = report["artifact_sha256"]
    assert "BTCUSDT_1h.parquet" in digests
    assert all(len(d) == 64 for d in digests.values())


def test_the_pinned_input_digest_names_the_parquet_on_disk(report: dict) -> None:
    """The notebook refuses any other input file, so the pin must name this one."""
    assert hashlib.sha256(DEFAULT_PARQUET.read_bytes()).hexdigest() == INPUT_SHA256
    assert report["artifact_sha256"]["BTCUSDT_1h.parquet"] == INPUT_SHA256


def test_timestamps_are_unique_and_monotone(frame: pl.DataFrame) -> None:
    ts = frame.get_column("ts_ms")
    assert ts.n_unique() == frame.height
    assert ts.is_sorted()


# -- the origin grid ----------------------------------------------------------


def test_grid_has_fifteen_origins() -> None:
    assert len(ORIGINS) == 15
    assert ORIGINS[0].label == "2020-01"
    assert ORIGINS[-1].label == "2025-11"


def test_every_origin_fits_inside_the_data_window() -> None:
    for origin in ORIGINS:
        assert origin.train_start >= DATA_START
        assert origin.test_end <= DATA_END


def test_block_index_is_decoupled_from_calendar_month() -> None:
    """Why origins are 5 months apart, as an executable claim.

    For fixed ``b`` the months visited form a coset of the subgroup generated by
    the spacing in Z12, of size ``12/gcd(s,12)``. At s=6 that is 2 — block index
    becomes a near-deterministic function of calendar month, and a significant
    beta1 is observationally equivalent to "February and August are harder".
    Only a spacing coprime to 12 decouples them.
    """
    assert gcd(ORIGIN_SPACING_MONTHS, 12) == 1

    # Block 1 starts on the origin itself, so it is the one block where the
    # coset argument is exact: all twelve months.
    assert len({origin.block(1)[0].month for origin in ORIGINS}) == 12

    # Blocks 2..6 start 30 *days* after their predecessor, not one calendar
    # month, so the coset argument is an idealisation there and coverage is
    # 7..11 rather than 12. The claim that survives measurement is the
    # comparative one, which is the claim the spacing rests on: every block
    # under 5-month spacing decouples far better than any block under 6-month.
    at_five = [
        len({origin.block(b)[0].month for origin in ORIGINS})
        for b in range(1, TEST_BLOCKS + 1)
    ]
    at_six = [
        len({origin.block(b)[0].month for origin in origin_grid(FIRST_ORIGIN, 6)})
        for b in range(1, TEST_BLOCKS + 1)
    ]
    assert min(at_five) >= 7, f"5-month spacing degraded: {at_five}"
    assert max(at_six) <= 3, f"6-month spacing is not the foil it was: {at_six}"
    assert all(f > s for f, s in zip(at_five, at_six)), (at_five, at_six)


def test_splits_are_ordered_and_disjoint() -> None:
    """train ∩ val = ∅ and (train ∪ val) ∩ test = ∅."""
    for origin in ORIGINS:
        assert origin.train_start < origin.train_sub_end
        assert origin.train_sub_end == origin.val_start
        assert origin.val_end == origin.test_start == origin.origin
        assert origin.test_end > origin.test_start


def test_training_sub_block_is_twenty_one_months() -> None:
    """The training sub-block is 21 months; 24 months would reach into validation."""
    for origin in ORIGINS:
        months = (
            (origin.train_sub_end.year - origin.train_start.year) * 12
            + origin.train_sub_end.month
            - origin.train_start.month
        )
        assert months == 21


# -- segment law --------------------------------------------------------------


def test_no_segment_spans_a_break(frame: pl.DataFrame) -> None:
    """FATAL. Windows validated by timestamp, never by positional index."""
    for seg in build_segments(frame):
        assert seg.end_ts - seg.start_ts == (seg.n_bars - 1) * HOUR_MS


def test_enumerated_windows_never_span_a_break(frame: pl.DataFrame) -> None:
    """The gap-densest origin is the one worth checking, not an average one."""
    origin = ORIGINS[5]  # 2022-02 — the worst training span in the committed table
    starts = enumerate_windows(frame, origin.train_start, origin.train_sub_end)
    assert starts, "even the densest origin has windows"
    assert len(starts) == len(set(starts))


def test_purge_holds_at_both_boundaries(frame: pl.DataFrame) -> None:
    """FATAL. The last target must end at the boundary, never past it.

    A window-span assertion, not a row-index one: row-level disjointness is true
    by construction and does not imply this.
    """
    for origin in ORIGINS[:3]:
        for lo, hi in (
            (origin.train_start, origin.train_sub_end),
            (origin.val_start, origin.val_end),
        ):
            starts = enumerate_windows(frame, lo, hi)
            if not starts:
                continue
            assert max(starts) + WINDOW_SPAN * HOUR_MS <= int(hi.timestamp() * 1000)


def test_measure_the_quantities_the_budget_calls_unmeasured(
    frame: pl.DataFrame, report: dict
) -> None:
    """Answers both open items in ``ORIGIN_WINDOW_BUDGET.md``.

    Neither the ``H == L`` count nor the zero-volume/zero-trade overlap has ever
    been measured, and the window cost arithmetic assumes both.
    """
    flat = int(frame.get_column("flat_bar").sum())
    zero_vol = int(frame.get_column("zero_volume").sum())
    zero_trd = int(frame.get_column("zero_trades").sum())
    both = int(frame.filter(pl.col("zero_volume") & pl.col("zero_trades")).height)
    unusable = int((~frame.get_column("usable")).sum())
    print(
        f"\nMEASURED  flat(H==L)={flat}  zero_volume={zero_vol}  "
        f"zero_trades={zero_trd}  same_bars={both}  unusable_total={unusable}"
    )
    assert zero_vol == report["zero_volume_bars"]
    assert zero_trd == report["zero_trade_bars"]


# -- budget: exact equality per origin ---------------------------------------


def test_closed_form_understates_where_a_segment_is_short(budgets) -> None:
    """The closed-form window count is not an identity, and this pins the gap.

    ``(bars - 119) - [119 x breaks + excluded]`` equals the segment-wise count
    only while every segment clears one window span. A segment of ``n < 120``
    contributes zero windows, but the closed form charges it ``n - 119``, a
    negative it then absorbs silently. Seven of fifteen origins are affected;
    2020-01 is understated by 137 windows.

    The closed form may never exceed the truth — that direction would mean
    windows counted that do not exist, which is a fatal leak class.
    """
    for budget in budgets:
        assert budget.windows_closed_form <= budget.windows_measured, (
            f"{budget.label}: closed form {budget.windows_closed_form:,} exceeds "
            f"measured {budget.windows_measured:,} — windows counted that do not exist"
        )


def test_measured_budget_matches_the_committed_table(budgets) -> None:
    """FATAL. Exact equality per origin — never against the pooled figure.

    Asserted pooled, this fires spuriously at fourteen of fifteen origins, gets
    loosened until it passes, and then can no longer distinguish positional
    drift from ordinary between-origin variation.
    """
    divergences = [
        f"{b.label}: committed (breaks={c[0]}, excl={c[1]}, kept={c[2]:,}) vs "
        f"measured (breaks={b.summary.break_runs}, "
        f"excl={b.summary.excluded_positions}, kept={b.windows_measured:,})"
        for b in budgets
        for c in [COMMITTED_TRAIN_BUDGET[b.label]]
        if (b.summary.break_runs, b.summary.excluded_positions, b.windows_measured)
        != c
    ]
    assert not divergences, (
        "docs/ORIGIN_WINDOW_BUDGET.md does not reproduce from the artifact.\n"
        + "\n".join(divergences)
    )


def test_training_counts_sit_in_the_declared_range(budgets) -> None:
    """13,520 … 15,217 training windows per origin, and not ~17,400."""
    counts = [b.windows_measured for b in budgets]
    assert max(counts) <= 15_217
    assert min(counts) >= 13_000
    assert max(counts) < 17_400


def test_tensor_fits_the_declared_budget(budgets) -> None:
    """The per-origin training tensor at K=12, float32, stays resident on the GPU.

    Measured 70.12 MB at the largest origin; 71 MB is the ceiling. Immaterial to
    the T4's 16 GB, kept as an assertion because the executor loads each split
    onto the device once.
    """
    largest = max(b.windows_measured for b in budgets)
    mb = largest * 96 * 12 * 4 / 1e6
    assert 70.0 < mb <= 71.0, f"training tensor is {mb:.2f} MB"


def test_every_test_block_start_is_admissible(budgets) -> None:
    """Test blocks hold 720 forecast origins, not 601.

    A training window must lie wholly inside its span. A *test* window may not:
    its 96-bar lookback reaching back across the boundary is past
    information legitimately available to a forecaster, and blocking it would
    make the evaluation unrealistically pessimistic. Counting test blocks the
    training way yields 601 of 720 on a perfectly clean block — a 16.5% phantom
    loss that would enter the block-coverage covariate as pure noise.
    """
    clean = sum(1 for b in budgets for n in b.test_block_starts if n == 720)
    assert clean == 74, f"{clean} of 90 blocks clean, expected 74"
    assert all(n <= 720 for b in budgets for n in b.test_block_starts)
